# Generated by Django 3.2.6 on 2021-12-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingrequest',
            name='myfiles',
        ),
    ]
