# Generated by Django 3.2.6 on 2021-12-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_remove_pricingrequest_myfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='myuploadfile_excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfiles', models.FileField(upload_to='excel')),
            ],
        ),
    ]
